version: '3.8'
services:
  mysql:
    container_name: monolith-mysql-db
    hostname: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret-password
      - MYSQL_DATABASE=monolith
      - MYSQL_USER=monolith
      - MYSQL_PASSWORD=arthur
  dev-server:
    container_name: monolith-app
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONOLITH_DB_HOST=mysql
