version: '3.8'
services:
  mysql:
    container_name: monolith-mysql-db
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret-password
      - MYSQL_DATABASE=monolith
      - MYSQL_USER=monolith
      - MYSQL_PASSWORD=arthur
